### ISSUE TITLE
[Vue warn]: Error in callback for immediate watcher "value": "TypeError: Cannot read property 'decoder' of undefined"

### ISSUE THREAD

**Issue by Matman94** [duoani/vue-scheduler#1]
Hi,
In Vue project I have Quasar framework, so maybe it possible, that is the problem that I cannot append Scheduler to project ?

**Errors from browser:** 

![image](https://user-images.githubusercontent.com/23061794/94116353-35fd0c80-fe4b-11ea-8285-ea7918574512.png)

**My code component:** 

![image](https://user-images.githubusercontent.com/23061794/94116449-5c22ac80-fe4b-11ea-98a1-ff1a8596b394.png)

Scheduler meets my requirements, so it would be a shame not to take advantage of it

**Comment by duoani** [comment]
I'm so sorry, that's my fault. This error will occur in version 1.0.5 when the VueScheduler component is by local registration. And I have resolved it in 1.0.6.
